config/routes.rb
Rails.application.routes.draw do
  resources :events do
    member do
      get 'edit_image', to: 'events#edit_image', as: 'edit_image' # Vista para editar la imagen
      patch 'update_image', to: 'events#update_image', as: 'update_image' # Actualizar la imagen
      delete 'delete_image', to: 'events#delete_image', as: 'delete_image' # Eliminar la imagen
    end
  end

  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }

  get ':name/my_events', to: 'events#my_events', as: 'my_events'
  get 'events_filters', to: 'events#events_filters', as: 'events_filters'
  get 'export', to: 'events#export', as: 'export', format: 'csv'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  validates :tipo_de_eventos, presence: true
  validates :reminder_datetime, presence: true
end

app/models/event_filter.rb
class EventFilter < ApplicationRecord
end

app/models/filtro.rb
class Filtro
  include ActiveModel::Model
  attr_accessor :tipo_evento, :fecha_inicio, :fecha_final
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable

  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

# EventsController
#
# Controlador para gestionar eventos.
require 'csv'
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @eventos = Event.all
  end

  def events_filters
    @eventos = if params[:tipo_de_eventos].present? || (params[:fecha_inicio].present? && params[:fecha_final].present?)
                 filtrar_eventos(params[:tipo_de_eventos], params[:fecha_inicio], params[:fecha_final]).paginate(
                   page: params[:page], per_page: 5
                 )
               else
                 Event.paginate(page: params[:page], per_page: 5)
               end
  end

  def show
    @evento
  end

  def edit; end

  def update
    if @evento.update(event_params)
      redirect_to @evento, notice: 'Evento editado exitosamente.'
    else
      render :edit
    end
  end

  def destroy
    @evento.destroy
    redirect_to events_path, notice: 'Evento eliminado exitosamente.'
  end

  def new
    @evento = current_user.events.new
  end

  def create
    @evento = current_user.events.new(event_params)

    if @evento.save
      ReminderJob.set(wait_until: @evento.reminder_datetime).perform_later(current_user.id, @evento.titulo,
                                                                           @evento.reminder_datetime)
      redirect_to events_filters_path, notice: 'Evento creado exitosamente.'
    else
      render :new
    end
  end

  def my_events
    @eventos = current_user.events
  end

  def edit_image
    @evento = Event.find(params[:id])
  end

  def update_image
    @event = Event.find(params[:id])
    @event.image.purge # Eliminar la imagen existente
    @event.image.attach(params[:event][:image]) # Adjuntar la nueva imagen

    redirect_to @event, notice: 'Imagen actualizada correctamente'
  end

  def delete_image
    @event = Event.find(params[:id]) # Utilizar params[:id] en lugar de params[:event_id]
    @event.image.purge # Eliminar la imagen
    redirect_to @event, notice: 'Imagen eliminada correctamente.'
  end

  def export
    tipo_de_eventos = params[:tipo_de_eventos]
    fecha_inicio = params[:fecha_inicio]
    fecha_final = params[:fecha_final]

    @eventos = filtrar_eventos(tipo_de_eventos, fecha_inicio, fecha_final)
    respond_to do |format|
      format.csv do
        send_data eventos_to_csv(@eventos), filename: 'eventos_exportados.csv'
      end
    end
  end

  private

  def eventos_to_csv(eventos)
    CSV.generate(headers: true) do |csv|
      # Agrega los encabezados
      csv << ['Titulo', 'Descripción', 'Fecha', 'Ubicación', 'Costo', 'Tipo de Evento']

      # Agrega los datos de cada evento que cumple con el filtro de tipo_de_evento
      eventos.each do |evento|
        csv << [evento.titulo, evento.descripcion, evento.fecha, evento.ubicacion, evento.costo, evento.tipo_de_eventos]
      end
    end
  end

  def filtrar_eventos(tipo_de_eventos, fecha_inicio, fecha_final)
    eventos = Event.all

    # Filtra por tipo_de_eventos si está presente y no es "Todos"
    eventos = eventos.where(tipo_de_eventos:) if tipo_de_eventos.present? && tipo_de_eventos != 'Todos'

    if fecha_inicio.present? && fecha_final.present?
      eventos = eventos.where(fecha: fecha_inicio.to_datetime.beginning_of_day..fecha_final.to_datetime.end_of_day)
    end
    eventos
  end

  def set_event
    @evento = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:titulo, :descripcion, :fecha, :ubicacion, :costo, :tipo_de_eventos,
                                  :reminder_datetime, :image)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reminder_controller.rb
class RemindersController < ApplicationController
  def create
    user_id = current_user.id 
    message = params[:reminder][:message]

    # Llamar al Active Job
    ReminderJob.perform_later(user_id, message)

    redirect_to events_path, notice: 'Recordatorio creado exitosamente.'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:user][:email])

    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to events_path, notice: 'Sesión iniciada exitosamente.'
    else
      flash.now[:alert] = 'Correo electrónico o contraseña incorrectos.'
      render :new
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, only: %i[create update]

  def new
    super
  end

  def create
    super do |resource|
      if resource.persisted?
        @user = resource
        UserMailer.with(user: @user).verification_email.deliver_later
        flash[:notice] = 'Se ha enviado un correo de verificación a tu dirección de correo electrónico.'
      end
    end
  end

  def edit
    @user = current_user
    super
  end

  def update
    super
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
  attr_accessible :name


  def new
  end

  def create
    super do |resource|
      BackgroundWorker.trigger(resource)
    end
  end

  protected

  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/event_planners_helper.rb
module EventPlannersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id @evento %>">
  <h1><%= @evento.titulo %></h1>
  <p><strong>Descripción:</strong> <%= @evento.descripcion %></p>
  <p><strong>Fecha:</strong> <%= @evento.fecha %></p>
  <p><strong>Fecha de recordatorio:</strong> <%= @evento.reminder_datetime %></p>
  <p><strong>Ubicación:</strong> <%= @evento.ubicacion %></p>
  <p><strong>Costo:</strong> <%= @evento.costo %></p>
  <%= image_tag url_for(@evento.image), class: "event-image large-image" if @evento.image.attached? %>
</div>

app/views/events/_form.html.erb
<%= form_with(model: evento, local: true, class:"form-wrapper") do |form| %>
  <% if evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(evento.errors.count, "error") %> Evento:</h2>
      <ul>
        <% evento.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field" data-controller="example">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, class:"form-control" %>
  </div>
  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, rows: 5, class:"form-control" %>
  </div>
  <div class="field">
    <%= form.label :fecha %>
    <%= form.datetime_field :fecha, class:"form-control" %>
  </div>
  <div class="field">
    <%= form.label :ubicacion %>
    <%= form.text_field :ubicacion, class:"form-control" %>
  </div>
  <div class="field">
    <%= form.label :costo %>
    <%= form.number_field :costo, class:"form-control" %>
  </div>
  <div class="field">
    <%= form.label :tipo_de_eventos, "Tipo de evento" %>
    <%= form.select :tipo_de_eventos, options_for_select(["Todos", "Público", "Privado"]), {}, class: "form-control" %>
  </div>
  <div class="field">
    <%= form.label :reminder_datetime, "Seleccionar fecha de recordatorio" %>
    <%= form.datetime_field :reminder_datetime, class:"form-control" %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, direct_upload: true %>
  </div>
  <div class="actions">
    <%= form.submit action_name=='new' ? 'Agregar Evento' : 'Guardar Cambios', class:"btn btn-success" %>
  </div>
<% end %>

app/views/events/delete_image.html.erb
<h1>Eliminar Imagen del Evento</h1>
<p>¿Estás seguro de que deseas eliminar la imagen del evento?</p>
<%= link_to 'Eliminar', delete_image_event_path(@evento), method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger' %>
<%= link_to 'Cancelar', event_path(@evento), class: 'btn btn-secondary' %>

app/views/events/edit.html.erb
<div class="start-flex ">
  <h1 class="text-center w-100">Editar Evento</h1>
  <%= render 'form', evento: @evento %>
  <div class="w-100 text-center">
    <%= link_to 'Volver', events_path, class:"btn btn-secondary" %>
  </div>
</div>

app/views/events/edit_image.html.erb
<h1>Editar Imagen del Evento</h1>
<%= form_with(model: @evento, url: update_image_event_path(@evento), method: :patch, local: true) do |form| %>
  <div class="field">
    <%= form.label :image, 'Nueva Imagen' %>
    <%= form.file_field :image %>
  </div>
  <%= form.submit 'Actualizar Imagen', class: 'btn btn-primary mt-3' %>
<% end %>

app/views/events/events_filters.html.erb
<%= form_tag events_filters_path, method: :get do %>
  <div class="row">
    <div class="col-lg-3 col-md-3 col-12">
      <div class="field">
        <%= label_tag :tipo_de_eventos, "Tipo de evento" %>
        <%= select_tag :tipo_de_eventos, options_for_select(["Todos", "Público", "Privado"]), class: "form-control" %>
      </div>
    </div>
    <div class="col-lg-3 col-md-3 col-12">
      <div class="field">
        <%= label_tag :fecha_inicio, "Fecha inicio" %>
        <%= date_field_tag :fecha_inicio, nil, class: "form-control" %>
      </div>
    </div>
    <div class="col-lg-3 col-md-3 col-12">
      <div class="field">
        <%= label_tag :fecha_final, "Fecha final" %>
        <%= date_field_tag :fecha_final, nil, class: "form-control" %>
      </div>
    </div>
    <div class="col-lg-3 col-md-3 col-12 d-flex" style="justify-content:center;align-items:center; gap:10px">
      <%= submit_tag "Filtrar", class: "btn btn-primary" %>
      <%= link_to 'Agregar Nuevo Evento', new_event_path, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<% if @eventos.present?%>
  <div class="events-wrapper">
    <div class="table-responsive">
      <div class="table-header-wrapper">
        <h1>Lista de Eventos</h1>
        <%= link_to 'Agregar Nuevo Evento', new_event_path, class: "btn btn-primary" %>
        <%= link_to 'Exportar Eventos a CSV', export_path(tipo_de_eventos: params[:tipo_de_eventos], fecha_inicio: params[:fecha_inicio], fecha_final: params[:fecha_final], format: "csv"), class: "btn btn-success" %>
      </div>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Imagen</th>
            <th>Titulo</th>
            <th>Descripción</th>
            <th>Fecha</th>
            <th>Ubicación</th>
            <th>Costo</th>
            <th>Tipo</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @eventos.each do |evento| %>
            <tr>
              <td>
                <%= image_tag url_for(evento.image), class: "event-image" if evento.image.attached? %>
              </td>
              <td><%= evento.titulo %></td>
              <td><%= evento.descripcion %></td>
              <td><%= evento.fecha %></td>
              <td><%= evento.ubicacion %></td>
              <td><%= evento.costo %></td>
              <td><%= evento.tipo_de_eventos %></td>
              <td>
                <%= link_to 'Mostrar', event_path(evento.id), class: "btn btn-primary" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="pagina-wrapper">
        <%= will_paginate @eventos %>
      </div>
    </div>
  </div>
<% else %>
  <p class="mt-5">No se encontraron eventos.</p>
<% end %>

app/views/events/index.html.erb
<% if user_signed_in? %>
  <div class="events-wrapper">
    <div class="table-responsive">
      <div class="table-header-wrapper">
        <h1>Lista de Eventos</h1>
        <%= link_to 'Agregar Nuevo Evento', new_event_path, class: "btn btn-primary" %>
      </div>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>id</th>
            <th>Imagen</th>
            <th>Titulo</th>
            <th>Descripción</th>
            <th>Fecha</th>
            <th>Ubicación</th>
            <th>Costo</th>
            <th>Tipo</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @eventos.each do |evento| %>
            <tr>
              <td><%= evento.id %></td>
              <td>
                <%= image_tag url_for(evento.image),class: "event-image" if evento.image.attached?  %>
              </td>
              <td><%= evento.titulo %></td>
              <td><%= evento.descripcion %></td>
              <td><%= evento.fecha %></td>
              <td><%= evento.ubicacion %></td>
              <td><%= evento.costo %></td>
              <td><%= evento.tipo_de_eventos %></td>
              <td>
                <%= link_to 'Mostrar', event_path(evento.id), class:"btn btn-primary" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/events/my_events.html.erb
<% if current_user %>
    <div class="events-wrapper">
      <div class="table-responsive">
        <div class="table-header-wrapper">
          <h1>Lista de Eventos</h1>
          <%= link_to 'Agregar Nuevo Evento', new_event_path, class: "btn btn-primary" %>
        </div>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Imagen</th>
              <!-- Nuevo encabezado para la columna de imagen -->
              <th>Titulo</th>
              <th>Descripción</th>
              <th>Fecha</th>
              <th>Ubicación</th>
              <th>Costo</th>
              <th>Tipo</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            <% @eventos.each do |evento| %>
              <tr>
                <td>
                  <%= image_tag url_for(evento.image), class: "event-image" if evento.image.attached? %>
                </td>
                <td><%= evento.titulo %></td>
                <td><%= evento.descripcion %></td>
                <td><%= evento.fecha %></td>
                <td><%= evento.ubicacion %></td>
                <td><%= evento.costo %></td>
                <td><%= evento.tipo_de_eventos %></td>
                <td>
                  <%= link_to 'Mostrar', event_path(evento), class: "btn btn-primary" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
<% end %>

app/views/events/new.html.erb
<div class="start-flex">
  <h1>Nuevo Evento</h1>
  <%= render 'form', evento: @evento %>
</div>

app/views/events/show.html.erb
<div class="start-flex">
  <%= render @evento %>
  <div class="button-wrapper">
    <%= link_to 'Editar', edit_event_path(@evento), class:"btn btn-warning", style:"color:white" %>
    <%= button_to 'Eliminar Evento', @evento, method: :delete, class: 'btn btn-danger' %>
    <%= link_to 'Volver', events_path, class:"btn btn-secondary" %>
    <%= link_to 'Editar imagen', edit_image_event_path(@evento.id), class:"btn btn-warning", style:"color:white"  %>
    <%= button_to 'Eliminar imagen', delete_image_event_path(@evento), method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger' %>
  </div>
</div>

app/views/events/update_image.html.erb
<h1>Imagen del Evento Actualizada</h1>
<p>La imagen del evento ha sido actualizada exitosamente.</p>
<%= link_to 'Volver al Evento', evento_path(@evento), class: 'btn btn-primary' %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "Team #2", root_path, class: "navbar-brand" %>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarText"
      aria-controls="navbarText"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
         <li class="nav-item active">
          <%= link_to "Eventos con filtro", events_filters_path, class: "btn btn-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Eventos públicos", events_path, class: "btn btn-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Mis eventos", my_events_path(current_user.name), class: "btn btn-link" %>
        </li>
        <li class="nav-item active">
          <%= button_to 'Cerrar sesión', destroy_user_session_path, method:
          :delete, class:"btn btn-link" %>
        </li>
         <li class="nav-item active">
          <%= link_to "Mi cuenta", edit_user_registration_path, class: "btn btn-link" %>
        </li>
        <% else %>
        <li class="nav-item active">
          <%= link_to 'Iniciar sesión', new_user_session_path %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Registrarse', new_user_registration_path %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<section class="home">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h1 class="title">Sistema de Gestión de Eventos</h1>
       
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>S5a1AdministradorDeEventosTeam02S5a1AdministradorDeEventos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="main-wrapper">
      <div class="container">
        <% if notice %>
          <p class="notice"><%= notice %></p>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>